### ISSUE TITLE
Can't fetch public jobs

### ISSUE THREAD

**Issue by mrbuku** [vincere-io/restful-api-support#10]
I have integrated the vincere API into my project, am trying to fetch all public jobs, but it keeps returning private jobs instead. I'm not quite sure why, I have read the documentation multiple times and can't figure out what I'm doing wrong.

Am using the following request query:

`/api/v2/job/search/fl=id,location,job_title,closed_date,industry,employment_type,summary,public_description,salary_from,salary_to,currency,company,city,location_name;sort=created_date desc?private_job=0`

I have tried the query without `private_job=0` at the end.

I would highly appreciate if you could point me in the right direction.

Thank you.

**Comment by phamvannam** [comment]
Hi @mrbuku 
I think you have miss our documentation
the search query shoud be like term

/api/v2/{entity}/search/fl=field_list;lang=en;sort=sort_fields;mlt.fl=moreLikeThis.fields?**q=query**&start=0&limit=25

the query should be start something like **q=private_job:0%23**

Please refer to the documentation for see more information [https://api.vincere.io/documentation.html#operation/searchGeneralInfo](https://api.vincere.io/documentation.html#operation/searchGeneralInfo)

**Comment by mrbuku** [comment]
Thanks @phamvannam, I have resolved the issue.
