### ISSUE TITLE
Need sample API usage demonstration in C#, Python or php or other platforms

### ISSUE THREAD

**Issue by mostafizursunny** [vincere-io/restful-api-support#3]
Hello,
I am implementing vincere.io api. I have generated API token and client id. Now, I am sending request as mentioned in "https://github.com/vincere-io/vincere-identity"
GET https://id.vincere.io/oauth2/authorize?client_id=123456&state=STATE&redirect_uri=https://YOUR_APP/redirect_uri&response_type=code

I have set my client id here and a test redirect_uri. I am getting invalid client error.

Do I need to add some subscription or configuration more to work with API? 
Is vincere API usage free ?
It will be great, if some sample codes are shared to implement API call. I need to get all jobs / all candidates / all activity as json from API call.

Please advice.

**Comment by mrbkiter** [comment]
Hi @mostafizursunny 

Could you provide full detail of your request and response? At which step you got stuck? 

For Vincere APIs, if you are an existing customer, it's free for use. Unfortunately we haven't developed sample projects. It would be planned for future.

**Comment by pradipkachhadiya** [comment]
Hi @mostafizursunny , 
You first you have to buy one vincere domain from vincere support. Like `sunny.vincere.io`
After you login into system then there setting icon that has marketplace item.
Click on marketplace there is second tab called `Api`


Generate one api_token and client_id and also set one `callback_url` for callback event after vincere login using oauth2.

Don't be hesitate. It's Simple to follow of your call.

**Comment by mostafizursunny** [comment]
Hi @pradipkachhadiya ,
Many thanks for the comment. I am registered user. I am seeing the sample curl call like:

curl -X GET -H "x-api-key: 2222222" -H "id-token:1111111" https://sunny.vincere.io/api/v2/candidate

Is x-api-key = Vincere API token from marketplace, and id-token = Client ID from marketplace ?

I am replacing the **x-api-key** and **id-token** collected from marketplace of my account and then issuing the curl call. But I am getting no response. Is the  **x-api-key** and **id-token** are Vincere API token and Client ID  of marketplace ?

**Comment by mrbkiter** [comment]
hi @mostafizursunny 

x-api-key is the api-key you got from marketplace.
For id-token it is the key you get from Vincere Identity. 

Vincere has provided authentication using OAuth2, that has documented in Vincere Identity on github (https://github.com/vincere-io/vincere-identity). 

Please follow steps in the documentation and let me know if you have any questions.
