### ISSUE TITLE
Issue in Vincere Login Process

### ISSUE THREAD

**Issue by pradipkachhadiya** [vincere-io/restful-api-support#4]
I have made my whole application using  Vincere API. Which is working for search data of jobs data.
`https://id.vincere.io/oauth2/authorize?client_id=my_client_id&state=STATE&redirect_uri=my_redirection_url&response_type=code`

Above url working perfect when I have add `CORS plugin to my browser`.
Otherwise it gives,
**Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers in preflight response.**

We all know it's not good practices to use plugin to make our functionality on way.

User who are not successfully login which are not installed `CORS plugin`.

Notes  :
-  My website project uploaded on https:
-  All functionality work if i have use CORS plugin.

Help me for this issue. Because i have already give much time for it.

**Comment by mrbkiter** [comment]
Hi @pradipkachhadiya 

Glad to hear you connect your APP with Vincere APIs. 

Before enabling CORS for our APIs, we need more info from you.

1. What is your Vincere URL? 
2. What kind of app are you developing? Is it sort of Web page using Vincere APIs? 

The more info you provide, the better. Any changes on prod would need Devops action, so it could take time.

**Comment by HaraldMayr** [comment]
Hi @mrbkiter 

Thank you for your response, we very much appreciate your help. @pradipkachhadiya and I are working on a software that allows recruiters to automatically generate personalized websites for contacting job candidates. We use https://www.jobdetails.ch/login as callback URL for the Vincere API, which allows us to obtain candidate and job details for these personalized websites.

We are collaborating with the recruiting agency Skybris, using the Vincere URL https://skybris.vincere.io/

We really appreciate your help. Please let us know if you would like to know more details, we are happy to explain further.

**Comment by mrbkiter** [comment]
@HaraldMayr 

Thanks for your info. I see that you have already sent support ticket to our Vincere support, and it is being processed. The point is, Vincere API Monitoring system is being built, so enabling CORS could be not allowed for the time being. Once things get ready, we would let you know. 

I will close this ticket. Please open new one in case you have any questions.
