### ISSUE TITLE
Vincere API v2 - Candidate Search - 400 Bad Request error

### ISSUE THREAD

**Issue by alexeysourcebreaker** [vincere-io/restful-api-support#7]
Hi,

Hope you can help me with a few technical issues.

I am trying to build integration with Vincere API v2 (candidate search https://api.vincere.io/documentation.html#operation/searchCandidate).

I am sending a GET request to https://companyname.vincere.io/api/v2/candidate/search/fl=id,name (I keep it simple here for now so I excluded all queries, etc.).
I added the following 2 request headers: _x-api-key_ and _id-token_, where _x-api-key_ is company's API key and _id-token_ is a valid id token that I got after passing through Vincere auth process.

Unfortunately, I get the following response from Vincere (400 BAD REQUEST):
```
{
    "message": "Data is invalid",
    "status": "FAILED",
    "httpStatus": "400",
    "errorCode": "QUERY_PARSE_FAIL",
    "errorId": "487ed120-b571-401b-9517-82f31892f56c",
    "errors": [
        "Parse exception {0}"
    ]
}
```

Please note the following:

- _x-api-key_ and _id-token_ should be working fine because if I change any of these I start getting 403 error back (which is expected).
- A few days ago we started receiving '_Search Server is currently unavailable_' error from Vincere. Before this point our search requests worked fine. But after Vincere search server went back online, our search requests stopped working with the above errors.

I would highly appreciate if you could help me understand what is causing this error.

Please let me know should you need more details.

Thank you!

Alexey

**Comment by phamvannam** [comment]
@alexeysourcebreaker 
I have try with your query on my tenant, it's work fine.
Can you tell me your tenant called on Vincere.
